### ISSUE TITLE
657 Strip raises tree builder error

### ISSUE THREAD

**Issue by mertzjames** [jakelandau/pykcd#1]
When trying to get the 657 strip I get the following error:

> bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

Running Python 3.5.1

**Comment by jakelandau** [comment]
lxml has been added to the dependencies list in setup.py. Is it installed on your environment?

**Comment by mertzjames** [comment]
No it isn't.  I'll make sure to install it.
